_name_or_path:
    value: divelab/Qwen3-0.6B-a2d-init
_wandb:
    value:
        cli_version: 0.25.1
        e:
            txp3tqdduaakxdexwind2fv4y0rqos7l:
                args:
                    - --num_proc
                    - "1"
                    - --loss_type
                    - CE
                    - --model_name_or_path
                    - divelab/Qwen3-0.6B-a2d-init
                    - --dataset_args
                    - Jotsna22/mix_60k_4096_Qwen3-4B_chunk10000_ntokens4096_greedy
                    - --max_length
                    - "4096"
                    - --num_train_epochs
                    - "5"
                    - --learning_rate
                    - "1e-4"
                    - --per_device_train_batch_size
                    - "4"
                    - --per_device_eval_batch_size
                    - "4"
                    - --gradient_accumulation_steps
                    - "1"
                    - --block_size
                    - "4"
                    - --loophole_enabled
                    - "False"
                    - --right_shift_logits
                    - "True"
                    - --eval_dataset_args
                    - openai/gsm8k[test:1319]
                    - --eval_strategy
                    - epoch
                    - --save_strategy
                    - epoch
                    - --logging_steps
                    - "10"
                    - --run_name
                    - qwen3-0.6b-bd3lm-block4-baseline-mix60k-len4096-5ep
                    - --output_dir
                    - /scratch/project/prj-02-pi-shuiwang-ji/atharvchagi/SC-models/a2d/Qwen3-0.6B-a2d-init/bd3lm/block4/len4096/baseline
                codePath: examples/a2d/bd3lm/sft.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1888556142592"
                        used: "45918564352"
                email: atharv.chagi@gmail.com
                executable: /home/atharvchagi_tamu.edu/.conda/envs/dllm/bin/python
                git:
                    commit: b90e305745d7a1f9258ee4a02b38c88d0a0f69ae
                    remote: git@github.com:atharvchagi/dllm_fork.git
                gpu: NVIDIA H200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-23bea4a3-5dbb-5bd8-4b0b-429cbb071620
                host: dgx006
                memory:
                    total: "2164176310272"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /scratch/user/atharvchagi_tamu.edu/dllm_fork/examples/a2d/bd3lm/sft.py
                python: CPython 3.10.20
                root: /scratch/user/atharvchagi_tamu.edu/dllm_fork/scripts/Loophole
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/etc/slurm/slurm.conf
                    cpus_on_node: "14"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: prj-02-pi-shuiwang-ji
                    job_cpus_per_node: "14"
                    job_end_time: "1789242773"
                    job_gid: "1881124278"
                    job_id: "525260"
                    job_name: interactive
                    job_nodelist: dgx006
                    job_num_nodes: "1"
                    job_partition: def
                    job_qos: standard
                    job_start_time: "1789134773"
                    job_uid: "1881124278"
                    job_user: atharvchagi_tamu.edu
                    jobid: "525260"
                    launch_node_ipaddr: 10.108.64.144
                    localid: "0"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dgx006
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "42343"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "44633"
                    pty_win_col: "188"
                    pty_win_row: "49"
                    script_context: prolog_task
                    srun_comm_host: 10.108.64.144
                    srun_comm_port: "39195"
                    step_gpus: "4"
                    step_id: "0"
                    step_launcher_port: "39195"
                    step_nodelist: dgx006
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /scratch/user/atharvchagi_tamu.edu/dllm_fork/scripts/Loophole
                    submit_host: slogin-01
                    task_pid: "1564194"
                    tasks_per_node: "1"
                    topology_addr: core.spine-su[1,3].2B-B-06-IB-CL[8,7],2B-A-07-IB-CL[6,5,4],2B-A-06-IB-CL[3,2,1],2B-D-07-IB-CL[24,23,22],2B-D-06-IB-CL[21,20,19],2B-C-07-IB-CL[18,17].dgx006
                    topology_addr_pattern: switch.switch.switch.node
                    umask: "0002"
                startedAt: "2026-09-11T14:04:47.057559Z"
                writerId: txp3tqdduaakxdexwind2fv4y0rqos7l
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.10.20
            "5": 0.25.1
            "6": 4.57.0
            "9":
                "1": transformers_trainer
            "12": 0.25.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - A2DQwen3LMHeadModel
attention_bias:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
block_size:
    value: 4
bos_token_id:
    value: 151643
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
distillation_policy:
    value: off_policy
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 0.1
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: true
half_precision_backend:
    value: auto
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_size:
    value: 1024
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 3072
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
kl_divergence_type:
    value: forward
kl_weight:
    value: 1
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 0.0001
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /scratch/project/prj-02-pi-shuiwang-ji/atharvchagi/SC-models/a2d/Qwen3-0.6B-a2d-init/bd3lm/block4/len4096/baseline/runs/Sep11_08-57-47_dgx006
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loophole_enabled:
    value: false
loophole_eval_self_cond_rate:
    value: 1
loophole_self_cond_rate:
    value: 0.9
loss_norm_type:
    value: token
loss_type:
    value: CE
loss_weight_type:
    value: scheduler
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 40960
max_steps:
    value: -1
max_window_layers:
    value: 28
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 596049920
model_type:
    value: a2d-qwen3
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 16
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 8
num_return_sequences:
    value: 1
num_train_epochs:
    value: 5
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /scratch/project/prj-02-pi-shuiwang-ji/atharvchagi/SC-models/a2d/Qwen3-0.6B-a2d-init/bd3lm/block4/len4096/baseline
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: true
pad_token_id:
    value: 151643
parallelism_config:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
right_shift_logits:
    value: true
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 1000000
run_name:
    value: qwen3-0.6b-bd3lm-block4-baseline-mix60k-len4096-5ep
save_on_each_node:
    value: false
save_only_model:
    value: true
save_safetensors:
    value: true
save_steps:
    value: 0.1
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
time_epsilon:
    value: 0.001
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.0
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weight_decay:
    value: 0
